"""followers

Revision ID: 414336c0c9c6
Revises: 6cf31ff6f108
Create Date: 2020-04-18 18:59:38.146862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414336c0c9c6'
down_revision = '6cf31ff6f108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
